
PUT http://localhost:8080/movies/2?title=Leon
Accept: application/json

###

POST http://localhost:8080/movies/1/rent?customer=Francesco
Accept: application/json

###

GET http://localhost:8080/movies
Accept: application/json
